### ISSUE TITLE
Error: Cannot return null for non-nullable field Option.value.

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/openusercss.org#65]
Captured by Sentry:

```
Error: Cannot return null for non-nullable field Option.value.
Cannot return null for non-nullable field Option.value.
Cannot return null for non-nullable field Option.value.
Cannot return null for non-nullable field Option.value.
Cannot return null for non-nullable field Option.value.
Cannot return null for non-nullable field Option.value.
Cannot return null for non-nullable field Option.value.
Cannot return null for non-nullable field Option.value.
Cannot return null for non-nullable field Option.value.
Cannot return null for non-nullable field Option.value.
  at ExpectedError (/browser.js:1:3142625)
  at _callee5/< (/browser.js:1:2956321)
  at tryCatch (/browser.js:1:2139543)
  at wrap/generator._invoke</< (/browser.js:1:2139151)
  at defineIteratorMethods/</prototype[method] (/browser.js:1:2139825)
...
(23 additional frame(s) were not displayed)
```

**Comment by DecentM** [comment]
Fixing this along with #57

**Comment by DecentM** [comment]
The query to reproduce the issue:
```
{
  latestThemes(limit: 6) {
    user {
      _id
      displayname
      username
      avatarUrl
      smallAvatarUrl
      lastSeen
      lastSeenReason
      bio
      donationUrl
      __typename
    }
    _id
    title
    description
    content
    createdAt
    lastUpdate
    version
    screenshots
    options {
      type
      label
      name
      value
      __typename
    }
    ratings {
      value
      __typename
    }
    __typename
  }
}
```

**Comment by DecentM** [comment]
Nope, still not fixed.

**Comment by DecentM** [comment]
This happens if a theme is saved that has a select type option, but the select type has no value. This should be checked for before saving.

**Comment by DecentM** [comment]
Should be fixed with https://github.com/OpenUserCSS/openusercss.org/commit/b6b28f6f172e112169a734bfdaa4846e9d5af4de and https://github.com/OpenUserCSS/openusercss.org/commit/d5a0bf6cc2aacbfc2c40faedb748221c681d7897
