### ISSUE TITLE
Searching is messed up

### ISSUE THREAD

**Issue by DecentM** [OpenUserCSS/openusercss.org#67]
I've gotten these so far:  

Searching for 'amazon', this is clientside
```
TypeError: Cannot assign to read only property 'value' of object '#<Object>'
    at http://localhost:5010/browser.js:162680:30
    at Array.filter (<anonymous>)
    at http://localhost:5010/browser.js:162671:45
    at Array.forEach (<anonymous>)
    at _callee$ (http://localhost:5010/browser.js:162670:27)
    at tryCatch (http://localhost:5010/browser.js:130920:40)
    at Generator.invoke [as _invoke] (http://localhost:5010/browser.js:131158:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:5010/browser.js:130972:21)
    at step (http://localhost:5010/browser.js:162640:191)
    at http://localhost:5010/browser.js:162640:361
```

Searching for 'github', this is in the API
```
Error: Cannot read property 'toString' of undefined
    at new ExpectedError (https://openusercss.org/browser.js:1:3145524)
    at https://openusercss.org/browser.js:1:2961700
    at tryCatch (https://openusercss.org/browser.js:1:2142342)
    at Generator._invoke (https://openusercss.org/browser.js:1:2141947)
    at Generator.prototype.(anonymous function) [as throw] (https://openusercss.org/browser.js:1:2142626)
    at step (https://openusercss.org/browser.js:1:2955185)
    at https://openusercss.org/browser.js:1:2955346
    at <anonymous>
```

**Comment by DecentM** [comment]
I've decided to revamp the backend that will take care of this and a bunch of other stuff.
