### ISSUE TITLE
Saving theme issue

### ISSUE THREAD

**Issue by Mottie** [OpenUserCSS/openusercss.org#69]
I was trying to upload [Discourse-Dark](https://github.com/StylishThemes/Discourse-Dark) and got the following 3 errors:

```sh
browser.js:1 TypeError: Cannot read property '2' of null
    at https://openusercss.org/browser.js:1:3141601
    at Array.forEach (<anonymous>)
    at https://openusercss.org/browser.js:1:3141414
    at tryCatch (https://openusercss.org/browser.js:1:2138408)
    at Generator._invoke (https://openusercss.org/browser.js:1:2138013)
    at Generator.prototype.(anonymous function) [as next] (https://openusercss.org/browser.js:1:2138692)
    at step (https://openusercss.org/browser.js:1:3140009)
    at https://openusercss.org/browser.js:1:3140212
    at new Promise (<anonymous>)
    at https://openusercss.org/browser.js:1:3139928
    at https://openusercss.org/browser.js:1:3142168
    at https://openusercss.org/browser.js:1:3050984
    at Generator.next (<anonymous>)
    at step (https://openusercss.org/browser.js:1:3046144)
    at https://openusercss.org/browser.js:1:3046347
    at new Promise (<anonymous>)
    at https://openusercss.org/browser.js:1:3046063
    at Sub.parseUserCSS (https://openusercss.org/browser.js:1:3051349)
    at boundFn (https://openusercss.org/browser.js:1:2748778)
    at Sub.invoker (https://openusercss.org/browser.js:1:2761396)
    at Sub.Vue.$emit (https://openusercss.org/browser.js:1:2829439)
    at Array.editor.on (https://openusercss.org/browser.js:1:3003518)
    at Editor.EventEmitter._signal (https://openusercss.org/browser.js:1:247951)
    at Editor.onDocumentChange (https://openusercss.org/browser.js:1:471960)
    at EditSession.EventEmitter._signal (https://openusercss.org/browser.js:1:247951)
    at EditSession.onChange (https://openusercss.org/browser.js:1:396587)
    at Document.EventEmitter._signal (https://openusercss.org/browser.js:1:247951)
    at Document.applyDelta (https://openusercss.org/browser.js:1:360097)
    at Document.insertMergedLines (https://openusercss.org/browser.js:1:357810)
    at Document.insert (https://openusercss.org/browser.js:1:356288)
    at EditSession.insert (https://openusercss.org/browser.js:1:406944)
    at Editor.insert (https://openusercss.org/browser.js:1:477435)
    at Editor.$handlePaste (https://openusercss.org/browser.js:1:475918)
    at Object.exec (https://openusercss.org/browser.js:1:451092)
    at https://openusercss.org/browser.js:1:439382
    at CommandManager.EventEmitter._emit.EventEmitter._dispatchEvent (https://openusercss.org/browser.js:1:247736)
    at CommandManager.exec (https://openusercss.org/browser.js:1:439925)
    at Editor.onPaste (https://openusercss.org/browser.js:1:475732)
    at HTMLTextAreaElement.onPaste (https://openusercss.org/browser.js:1:219715)
    at HTMLTextAreaElement.wrapped (https://openusercss.org/browser.js:1:2091242)
console.(anonymous function) @ browser.js:1
```

```sh
browser.js:1 Uncaught (in promise) TypeError: Cannot destructure property `props` of 'undefined' or 'null'.
    at browser.js:1
    at Generator.throw (<anonymous>)
    at step (browser.js:1)
    at browser.js:1
    at <anonymous>
```

browser.js:1 Error: GraphQL error: Cannot read property '2' of null
    at new ApolloError (browser.js:1)
    at browser.js:1
    at <anonymous>
```

**Comment by Mottie** [comment]
Sorry this somehow was duped... GitHub lag?!
